name: Bump package in dependent repos on release

on:
  release:
    types:
      - published

jobs:

  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumping
        uses: derberg/org-projects-dependency-manager@6729190df24122200a0ffdac2318acb7a7c9df36
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          repos_to_ignore: "piontek"
          packagejson_path: ./gleboko
          committer_username: pomidor
          committer_email: pomidor@pomidor.com
          commit_message_prod: "fix: update internal production dependencies"
          commit_message_dev: "chore: update internal development dependencies"
