name: Bump package in dependent repos on releases

on:
  release:
    types:
      - published

jobs:

  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumping
        uses: BOLT04/custom-dependabot-for-your-github-org@79ef59aaf6c33e1e00a342a45eb28cd138e7c08e
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          repos_to_ignore: "piontek"
          committer_username: pomidor
          committer_email: pomidor@pomidor.com
          packagejson_path: ./gleboko
