name: Bump package in dependent repos on releases

on:
  release:
    types:
      - published

jobs:

  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumping
        uses: derberg/npm-dependency-manager-for-your-github-org@8055788187e25c93d92fdc415f1c3f68755c7ef9
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          repos_to_ignore: "piontek"
          committer_username: pomidor
          committer_email: pomidor@pomidor.com
          packagejson_path: ./gleboko
          branch_name: dupa
