name: Bump package in dependent repos on releases

on:
  release:
    types:
      - published

jobs:

  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumping
        uses: derberg/npm-dependency-manager-for-your-github-org@af03d24e5b96720ab09884134e3f79dac6414019
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          repos_to_ignore: "piontek"
          committer_username: pomidor
          committer_email: pomidor@pomidor.com
          packagejson_path: ./gleboko
          base_branch: dupa
