name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@07d5b5f116c2e121ce7a9736ccc5230a02031abb
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          files_to_ignore: global-workflow.yml, bump-on-release.yml
          repos_to_ignore: website, sunshine
          committer_username: santiago-bernabeu
          committer_email: my-email@me.com
          commit_message: "ci: update global workflows"
