name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@44471eb062aa1459373952e4e936368d8c3002f5
        with:
          github_token: ${{ secrets.CUSTOM_TOKENo }}
