name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@20fe44d13ec1363fb6bc7a1d912e46737de225b5
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          files_to_ignore: global-workflow.yml, bump-on-release.yml
          repos_to_ignore: website, sunshine
          committer_username: santiago-bernabeu
          committer_email: my-email@me.com
          commit_message: "ci: update global workflows"
