name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: RostiMelk/global-workflows-support@cb0c286d231bde197af2dc20269e6acbbef06c0f
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          files_to_ignore: global-workflow.yml
          repos_to_ignore: website,lukasz-lab.github.io
          committer_username: santiago-bernabeu
          committer_email: my-email@me.com
          commit_message: "ci: update global workflows"
          topics_to_include: lysy,maniek
