name: Global workflow to rule all other worklows

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@9a4e9676898483000f62dfcafe909e085bb5038f
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
