name: Global workflow to rule all other worklows

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@0abd8afd981f241eaac849a0327527b0c5f7a307
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
