name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@c1208bec668d5abab0007d896944f2151666f9f9
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          files_to_ignore: global-workflow.yml, bump-on-release.yml
          repos_to_ignore: website, sunshine,lukasz-lab.github.io
          committer_username: santiago-bernabeu
          committer_email: my-email@me.com
          commit_message: "ci: update global workflows"
