name: Global workflow to rule all other worklows

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@d63bab0a6a4b92d029564ab1e7a022c9512d458d
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
