name: Global workflow to rule all other workflows

on:
  #push:
  #  branches: [ master ]
  issues:
    types: [opened, edited, milestoned]
jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@2e9dd449b6718c3dabfbf3231e9c5b5c878e594c
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
