name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-actions-support@3809d21ce78b0d2048cd67acd9c3b90f19fa6e6e
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          files_to_ignore: global-workflow.yml, bump-on-release.yml
          repos_to_ignore: website, sunshine
          committer_username: santiago-bernabeu
          committer_email: my-email@me.com
          commit_message: "ci: update global workflows"
