name: Global workflow to rule all other workflows

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      repo_name:
        description: |
          You can specify name of the repository where workflows should be pushed manually. As long as repository is not ignored by workflow settings.
          If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
        required: false

jobs:

  replicate_changes:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: derberg/global-workflows-support@29c1c9b34c8df2055ff85a64571cbb822a496d10
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          files_to_ignore: global-workflow.yml,bump-on-release.yml
          repos_to_ignore: website,lukasz-lab.github.io
          committer_username: santiago-bernabeu
          committer_email: my-email@me.com
          commit_message: "ci: update global workflows"
          exclude_forked: true
          branches: .*-release,main
          #topics_to_include: lysy,maniek
